# Generated by Django 3.2 on 2021-04-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('telefone', models.CharField(max_length=15, verbose_name='telefone')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('mensagem', models.CharField(max_length=500, verbose_name='Mensagem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
